### ISSUE TITLE
Offset functionality not working?

### ISSUE THREAD

**Issue by cnallamn** [mindspank/WaterfallChart#2]
Hi,

I have tried using the latest waterfall chart which has offset option, but we see this option is for setting for only 1st bar, not all the bar's.
![g2n waterfall](https://cloud.githubusercontent.com/assets/11518166/8716654/e4c7e352-2bb0-11e5-8479-0e4f819d3e6c.png)

I have compared the same set of data between QlikView and QlikSense. attached the image for your reference with expected output.

Please let us know how this can be achieved.

Thank you
Chenna

**Comment by mindspank** [comment]
Yes that is correct, it will only offset the first bar, that is by design.
The following bars will automatically offset based on previous bars.

**Comment by cnallamn** [comment]
Thank you.

But is there any way to change the functionality to represent the chart
with the one I have shown in the image.

Regards,

Chenna

_From:_ Alexander Karlsson [mailto:notifications@github.com]
_Sent:_ 16 July 2015 12:35
_To:_ mindspank/WaterfallChart
_Cc:_ cnallamn
_Subject:_ Re: [WaterfallChart] Offset functionality not working? (#2)

Yes that is correct, it will only offset the first bar, that is by design.
The following bars will automatically offset based on previous bars.

**Comment by mindspank** [comment]
Nope, that seems way to case specific to fit into a generic waterfall chart.
It's probably better to fork this project and roll your own.

**Comment by cnallamn** [comment]
Hi,

Can you please advise what changes in.js file would get me required
solution.

Thank you.

Best Regards,

Chenna

_From:_ Alexander Karlsson [mailto:notifications@github.com]
_Sent:_ 17 July 2015 10:32
_To:_ mindspank/WaterfallChart
_Cc:_ cnallamn
_Subject:_ Re: [WaterfallChart] Offset functionality not working? (#2)

Nope, that seems way to case specific to fit into a generic waterfall chart.
It's probably better to fork this project and roll your own.
